language: python
python:
-   '2.7'
-   '3.4'
-   '3.5'
-   '3.6'
before_install:
- chmod +x ci/run_tests.sh
- travis_retry pip install --upgrade pip
- travis_retry pip install ipython
- travis_retry pip install ipywidgets
- travis_retry pip install requests
install:
- travis_retry pip install --upgrade pip
- travis_retry pip install tox
- travis_retry pip install sphinx
- travis_retry pip install sphinx_rtd_theme
script:
- cd docs
- make html
- cd -
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN
  on:
    branch: master
target_branch: gh-pages
committer-from-gh: true
script:
-   ./ci/run_tests.sh