language: python
python:
-   '3.6'
before_install:
- sudo apt-get install -y pandoc
- travis_retry pip install --upgrade pip
- travis_retry pip install ipython
- travis_retry pip install ipywidgets
- travis_retry pip install requests
install:
- travis_retry pip install --upgrade pip
- travis_retry pip install tox
- travis_retry pip install sphinx
- travis_retry pip install sphinx_rtd_theme
script:
-   ./ci/run_tests.sh
-   ./ci/update_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN
target_branch: gh-pages
committer-from-gh: true
