language: python
python:
  - '3.6' # add more versions
install:
  - sudo apt-get install -y pandoc
  - travis_retry pip install --upgrade pip
  - travis_retry pip install ipython
  - travis_retry pip install ipywidgets
  - travis_retry pip install requests
  - travis_retry pip install tox
script:
  - ./ci/run_tests.sh
  - ./ci/update_docs.sh # keep this so that example notebooks are executed on every commit
deploy:
  - provider: pages
    skip_cleanup: true
    on:
      tags: true # do not update documentation unless it is a tagged commit
    local_dir: docs/_build/html
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    committer-from-gh: true
