channels:
  - conda-forge
  - pyviz
  - defaults
dependencies:
  - cartopy
  - pip:
    - ipykernel
    - ipywidgets>=7.1.0rc1
    - matplotlib
    - netCDF4
    - xarray
    - seaborn
    - holoviews
    - bokeh
    - cython
    - cartopy
    - pyshp
    - drilsdown
    
