name: DRILSDOWN
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - jupyter
  - jupyterlab
  - pip
  - fastparquet
  - psutil
  - fsspec
  - ipykernel
  - ipywidgets>=7.1.0rc1
  - matplotlib
  - xarray
  - cython
  - cartopy
  - pyshp
  - pip:
    - drilsdown
    
